test:
  adapter: postgres
  database: dbname=goboilerplatetest sslmode=disable user=postgres password=123456

development:
  adapter: postgres
  database: dbname=goboilerplatedevelopment sslmode=disable user=postgres password=123456

production:
  adapter: postgres
  database: dbname=goboilerplateproduction sslmode=disable user=postgres password=123456