test:
  adapter: postgres
  database: dbname=databasename sslmode=disable user=postgres password=123456

development:
  adapter: postgres
  database: dbname=databasename sslmode=disable user=postgres password=123456

production:
  adapter: postgres
  database: dbname=databasename sslmode=disable user=postgres password=123456